"""Added anomaly table

Revision ID: 13c1c59c5e61
Revises: 430de2325b53
Create Date: 2026-08-27 16:46:49.232061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c1c59c5e61'
down_revision: Union[str, Sequence[str], None] = '430de2325b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('deviation_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('root_cause_hint', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_entity_id'), 'anomaly_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_entity_type'), 'anomaly_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_anomaly_events_id'), 'anomaly_events', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_metric_id'), 'anomaly_events', ['metric_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_observation_id'), 'anomaly_events', ['observation_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_tenant_id'), 'anomaly_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_events_tenant_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_observation_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_metric_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_entity_type'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_entity_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
