"""dropped anomaly table

Revision ID: 1c33c5f7c3d9
Revises: 13c1c59c5e61
Create Date: 2026-08-27 17:21:47.075562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c33c5f7c3d9'
down_revision: Union[str, Sequence[str], None] = '13c1c59c5e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
