"""Added RBAC to User

Revision ID: 24bae145bdbe
Revises: 005cc3e81f48
Create Date: 2026-08-20 18:08:57.559991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bae145bdbe'
down_revision: Union[str, Sequence[str], None] = '005cc3e81f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
