"""Added table forecast model

Revision ID: 2f8489840121
Revises: 3df6f1b92b82
Create Date: 2026-08-20 16:24:48.833964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8489840121'
down_revision: Union[str, Sequence[str], None] = '3df6f1b92b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('horizon', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='forcastmodelstatus'), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_models_id'), 'forecast_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_models_id'), table_name='forecast_models')
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
