"""Added Roles to user table

Revision ID: 4133c109b3b8
Revises: 24bae145bdbe
Create Date: 2026-08-21 10:47:08.332137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4133c109b3b8'
down_revision: Union[str, Sequence[str], None] = '24bae145bdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_forecast_runs_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index(op.f('ix_forecast_models_id'), table_name='forecast_models')
    op.drop_table('forecast_models')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_business_units_id'), table_name='business_units')
    op.drop_table('business_units')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_metrics_id'), table_name='forecast_metrics')
    op.drop_table('forecast_metrics')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('facilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('facility_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('facilities_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('facilities_pkey'))
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_table('forecast_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('forecast_metrics_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forecast_metrics_pkey'))
    )
    op.create_index(op.f('ix_forecast_metrics_id'), 'forecast_metrics', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forecast_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('predicted_value', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('lower_bound', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('upper_bound', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], name=op.f('forecast_results_metric_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('forecast_results_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forecast_results_pkey'))
    )
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_table('business_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('business_units_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_units_pkey'))
    )
    op.create_index(op.f('ix_business_units_id'), 'business_units', ['id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('quality_flag', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], name=op.f('observations_metric_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('observations_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('observations_pkey'))
    )
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_table('forecast_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('horizon', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='forcastmodelstatus'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], name=op.f('forecast_models_metric_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('forecast_models_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forecast_models_pkey'))
    )
    op.create_index(op.f('ix_forecast_models_id'), 'forecast_models', ['id'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='forecastrunstatus'), autoincrement=False, nullable=False),
    sa.Column('training_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('training_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('forecast_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('forecast_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('input_window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('input_window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('performance_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['forecast_models.id'], name=op.f('forecast_runs_model_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('forecast_runs_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forecast_runs_pkey'))
    )
    op.create_index(op.f('ix_forecast_runs_id'), 'forecast_runs', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('regions_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('regions_pkey'))
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='tenantstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    # ### end Alembic commands ###
