"""Updated User table RBAC

Revision ID: 41d8c4a6c54b
Revises: f1d09b716e4c
Create Date: 2026-08-21 11:23:32.634683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d8c4a6c54b'
down_revision: Union[str, Sequence[str], None] = 'f1d09b716e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('super_admin', 'operational_manager', 'analyst', 'viewer', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
