"""Updated scenario table

Revision ID: 5044c2e2655f
Revises: 853d16735b97
Create Date: 2026-08-28 09:54:29.194610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5044c2e2655f'
down_revision: Union[str, Sequence[str], None] = '853d16735b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_simulations', 'operational_impact',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_simulations', 'operational_impact',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    # ### end Alembic commands ###
