"""Added again forecast run table

Revision ID: 7c2f4f2a4d58
Revises: eaee4705de87
Create Date: 2026-08-26 15:12:37.969973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2f4f2a4d58'
down_revision: Union[str, Sequence[str], None] = 'eaee4705de87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'FAILED', 'COMPLETED', name='forecastrunstatus'), nullable=False),
    sa.Column('training_start', sa.DateTime(), nullable=True),
    sa.Column('training_end', sa.DateTime(), nullable=True),
    sa.Column('forecast_start', sa.DateTime(), nullable=True),
    sa.Column('forecast_end', sa.DateTime(), nullable=True),
    sa.Column('input_window_start', sa.DateTime(), nullable=True),
    sa.Column('input_window_end', sa.DateTime(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['forecast_models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_id'), 'forecast_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_runs_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
