"""Added scenario table

Revision ID: 853d16735b97
Revises: 3af93b684edd
Create Date: 2026-08-27 17:49:20.286569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853d16735b97'
down_revision: Union[str, Sequence[str], None] = '3af93b684edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('input_parameters', sa.JSON(), nullable=False),
    sa.Column('operational_impact', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cost_change', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('resource_consumption_change', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('failure_probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('performance_degradation', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('predicted_savings', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('recommendation_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scenariosimulationstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_simulations_id'), 'scenario_simulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_simulations_id'), table_name='scenario_simulations')
    op.drop_table('scenario_simulations')
    # ### end Alembic commands ###
