"""Added again optimization table

Revision ID: 9fc2c7854269
Revises: e82868e43d0b
Create Date: 2026-08-28 10:48:11.711827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fc2c7854269'
down_revision: Union[str, Sequence[str], None] = 'e82868e43d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('estimated_cost_savings', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('estimated_operational_impact', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('estimated_resource_change', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('estimated_performance_improvement', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_recommendations_created_by'), 'optimization_recommendations', ['created_by'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_entity_id'), 'optimization_recommendations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_entity_type'), 'optimization_recommendations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_id'), 'optimization_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_recommendation_type'), 'optimization_recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_source_id'), 'optimization_recommendations', ['source_id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_source_type'), 'optimization_recommendations', ['source_type'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_tenant_id'), 'optimization_recommendations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_recommendations_tenant_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_source_type'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_source_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_recommendation_type'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_entity_type'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_entity_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_created_by'), table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    # ### end Alembic commands ###
