"""add optimization tables

Revision ID: a71ae8c39c36
Revises: cbd588035162
Create Date: 2026-08-26 11:48:55.425419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71ae8c39c36'
down_revision: Union[str, Sequence[str], None] = 'cbd588035162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_strategies_id'), 'optimization_strategies', ['id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast_results.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['forecast_metrics.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_table('optimization_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('expected_cost', sa.Float(), nullable=True),
    sa.Column('expected_savings', sa.Float(), nullable=True),
    sa.Column('operational_impact', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('improvement_percentage', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['optimization_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_evaluations_id'), 'optimization_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_evaluations_id'), table_name='optimization_evaluations')
    op.drop_table('optimization_evaluations')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_optimization_strategies_id'), table_name='optimization_strategies')
    op.drop_table('optimization_strategies')
    # ### end Alembic commands ###
