"""Updated User table

Revision ID: bb9b901411af
Revises: 8df6eb1fd568
Create Date: 2026-08-21 11:26:30.325337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9b901411af'
down_revision: Union[str, Sequence[str], None] = '8df6eb1fd568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
