"""Added a role to User table

Revision ID: be9a4490862b
Revises: b94bafd233b9
Create Date: 2026-08-21 10:55:06.219322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9a4490862b'
down_revision: Union[str, Sequence[str], None] = 'b94bafd233b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
