"""Update tenant table

Revision ID: cb468c86dd69
Revises: c5e1e5ce6f68
Create Date: 2026-08-21 14:42:56.448971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb468c86dd69'
down_revision: Union[str, Sequence[str], None] = 'c5e1e5ce6f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('organization_name', sa.String(length=30), nullable=False))
    op.add_column('tenants', sa.Column('industry', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('tenants', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'industry')
    op.drop_column('tenants', 'organization_name')
    # ### end Alembic commands ###
