"""Updated scenario table for second time

Revision ID: ccf04cbf1554
Revises: 5044c2e2655f
Create Date: 2026-08-28 10:07:22.944280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf04cbf1554'
down_revision: Union[str, Sequence[str], None] = '5044c2e2655f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_simulations', 'cost_change',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True)
    op.alter_column('scenario_simulations', 'resource_consumption_change',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True)
    op.alter_column('scenario_simulations', 'failure_probability',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               nullable=True)
    op.alter_column('scenario_simulations', 'performance_degradation',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               nullable=True)
    op.alter_column('scenario_simulations', 'predicted_savings',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True)
    op.alter_column('scenario_simulations', 'recommendation_summary',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenario_simulations', 'recommendation_summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scenario_simulations', 'predicted_savings',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False)
    op.alter_column('scenario_simulations', 'performance_degradation',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               nullable=False)
    op.alter_column('scenario_simulations', 'failure_probability',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               nullable=False)
    op.alter_column('scenario_simulations', 'resource_consumption_change',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False)
    op.alter_column('scenario_simulations', 'cost_change',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False)
    # ### end Alembic commands ###
