"""Updated User table

Revision ID: f1d09b716e4c
Revises: be9a4490862b
Create Date: 2026-08-21 11:16:15.259683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d09b716e4c'
down_revision: Union[str, Sequence[str], None] = 'be9a4490862b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONAL_MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
